---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ceph-nvmeof-keyring-gw-a
  namespace: nvmeof-gateway
spec:
  encryptedData:
    keyring: AgDZ+swLqF6YFjzJLHF51f2tnIMsgOBn2UbfRdsGOIVkMe4grB/Ig7opARfMifTqPcQ4a93HmDH56Qs9JW8yGlEMsjXjA6iZ3aOAiXPdytP4o0RViqhEoo+fp5R9VZAdx4XmLcKJ6XGAv/CWbJ9XXZuWqW64uCTUaQaZ8jC2hZErUqGZ/UFrZ5ENVkTM6QVs65B+uwqQzRSNj1+g3PRu5IfWvyvN7hdVS1vNLaZXkdBIWQI760gVKowJP0uy1JKO9lRW6wxm6dK4fsxHseanZd9i8PkjfT/Nury46KLy+Vd9iJRVtt7Jdbm9yDSo25Xug9Q/61Ds+T1O2FfzUzeB2VMjnlA8xtA9D103bdCbyklck2gi63ncxBPfKbw03yQv4Z05/iJME4vzdFOUF3YQIc6TGviaLtym4Ja3PS9izhv694KyR26HoglEFbGDiuQZPCglc+aXlgv7ZC7t4TEfCT10SrVj9c2pZyJvuS7az3Qwy8akfC5IQrXRa64tvyuscFx5fTgiwfVH5UxXMQyHDJPqNlAjUFqoL4EoVIiDerW4nMyppnVdxazZ7+1Ygc1Pa2QGl9awuZCmagfs3okFEk90qhclGDmjCer9Qai3EpJQ351Qj0T4uNB2huVt9WpjOlBVOnunH0WW+i+nASIDSDL0dqz4eOvylURij6NIRpewG6fG7QhzodIJEDQ5rPFCG9zn+ZrCEUVRGcNCFIV22yGH40u0CDlan/tdl8tuvk+pri5jPS3xCj09T9fjUXYeFFqRWEjWlqGSH/rj+KNin4We77kckw==
  template:
    metadata:
      name: ceph-nvmeof-keyring-gw-a
      namespace: nvmeof-gateway
    type: Opaque
