apiVersion: v1
kind: Service
metadata:
  name: nvmeof-gw-b
  namespace: nvmeof-gateway
  labels:
    app: nvmeof
    gateway: gw-b
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.144.27.225"
spec:
  type: LoadBalancer
  selector:
    app: nvmeof
    gateway: gw-b
  ports:
    - { name: grpc,      port: 5500, targetPort: 5500, protocol: TCP }
    - { name: nvme-tcp,  port: 4420, targetPort: 4420, protocol: TCP }
    - { name: discovery, port: 8009, targetPort: 8009, protocol: TCP }
