apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvmeof-gateway

resources:
  - 10-ceph-config.yaml
  - 15-nvmeof-config.yaml
  - 11-keyring-gw-a.sealed.yaml
  - 11-keyring-gw-b.sealed.yaml
  - 20-deployment-gw-a.yaml
  - 20-deployment-gw-b.yaml
  - 30-service-gw-a.yaml
  - 30-service-gw-b.yaml
